{
 "title": "Python File",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "request_processing_seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_processing_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "python_info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "python_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "spent processing request",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_processing_seconds_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "python_gc_objects_collected_total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "python_gc_collections_total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "python_gc_objects_uncollectable_total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}