{
 "title": "Drift Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "PHT Drift",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_pht_drift_detection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IKS Drift",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_iks_drift_detection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NM Drift",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_nm_drift_detection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Plover Drift",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_plover_drift_detection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MEAN ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 6 },
   "targets": [
    { "expr": "layer_output_testing_mean", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "STD",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 12 },
   "targets": [
    { "expr": "layer_output_testing_std", "legendFormat": "__auto" }
   ]
  }
 ]
}