
version: '3.8'

services:
  
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    volumes:
      - C:/software/lab/prometheus-2.51.2.windows-amd64/prometheus.yml:/etc/prometheus/prometheus.yml

  app:
    build: .
    ports:
      - "8000:8000"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring


  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"  # Simplified port binding
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      prometheus-job: nodeexporter
      
      
      
      