# Use an official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the Python dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files to the working directory
COPY . .

# Expose the port where Prometheus metrics are served
EXPOSE 8000

# Run the deployed_model.py script when the container starts
# 'tail -f /dev/null' is added to keep the container running after execution
CMD ["sh", "-c", "python deployed_model.py && tail -f /dev/null"]
