{
 "title": "online-based detector dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "data_pht_drift_detection ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_pht_drift_detection ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "data_iks_drift_detection ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_iks_drift_detection ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "data_nm_drift_detection ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_nm_drift_detection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "data_plover_drift_detection ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_plover_drift_detection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "data_cd_drift_detection ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_cd_drift_detection ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "layer_output_testing_std",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 5 },
   "targets": [
    { "expr": "layer_output_testing_std", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "layer_output_testing_mean ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 13 },
   "targets": [
    { "expr": "layer_output_testing_mean", "legendFormat": "__auto" }
   ]
  }
 ]
}