
version: '3.8'

services:
  
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    volumes:
      - C:/software/lab/prometheus-2.51.2.windows-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    restart: always
    networks:
      - monitoring


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring


  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"  # Simplified port binding
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      prometheus-job: nodeexporter
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
