{
 "title": "dashboard STD, Mean, Distribution",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Distribution",
   "type": "histogram",
   "gridPos": { "h": 41, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "layer_output_distribution_bucket{epoch=~\"0\", cycle=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer_output_mean{epoch=~\"^[0-4]$\", cycle=\"0\"}",
     "legendFormat": "Epoch:{{epoch}}"
    }
   ]
  },
  {
   "title": "STD",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer_output_std_dev{epoch=~\"^[0-4]$\", cycle=\"0\"}",
     "legendFormat": "Epoch:{{epoch}}"
    }
   ]
  }
 ]
}