import pandas as pd
from evidently.report import Report
from evidently.metric_preset import DataDriftPreset


def main():
    # Simulated previous data for reference
    previous_means = [0.5, 0.6, 0.4, 0.55]  # example data
    previous_stds = [0.1, 0.15, 0.2, 0.12]  # example data

    # Current test results (you would replace these lists with those generated by your model testing)
    current_means = [0.6, 0.7, 0.5, 0.65]  # you'll generate these in your testing phase
    current_stds = [0.12, 0.18, 0.22, 0.15]  # you'll generate these in your testing phase

    # Create DataFrames
    reference_data = pd.DataFrame({
        'means': previous_means,
        'stds': previous_stds
    })

    current_data = pd.DataFrame({
        'means': current_means,
        'stds': current_stds
    })

    # Create Evidently Report
    drift_report = Report(metrics=[DataDriftPreset()])
    drift_report.run(reference_data=reference_data, current_data=current_data)

    # Save the report to an HTML file
    drift_report.save_html('drift_report.html')

    # Optionally, print the report to Jupyter Notebook or another Python environment that supports HTML rendering
    print("Report generated and saved as 'drift_report.html'.")


if __name__ == "__main__":
    main()
